# Generated by Django 5.2.7 on 2025-10-27 16:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISTEMA', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaofluxo',
            name='fluxo',
        ),
        migrations.AlterField(
            model_name='fluxopadrao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimentacaofluxo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos do Django.', related_name='usuarios_sistema', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões específicas.', related_name='usuarios_sistema', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterModelTable(
            name='fluxopadrao',
            table='fluxos_padrao',
        ),
        migrations.CreateModel(
            name='EtapaInstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_etapa', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('perfil_aprovador', models.CharField(choices=[('administrador', 'Administrador'), ('padrao', 'Padrão')], default='padrao', max_length=20)),
                ('concluida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SISTEMA.setor')),
            ],
            options={
                'verbose_name': 'Etapa da Instância',
                'verbose_name_plural': 'Etapas da Instância',
                'db_table': 'etapas_instancia',
                'ordering': ['fluxo_instancia', 'ordem_etapa'],
            },
        ),
        migrations.AlterField(
            model_name='movimentacaofluxo',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SISTEMA.etapainstancia'),
        ),
        migrations.CreateModel(
            name='FluxoInstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('finalizado', models.BooleanField(default=False)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='SISTEMA.fluxopadrao')),
            ],
            options={
                'verbose_name': 'Fluxo em Execução',
                'verbose_name_plural': 'Fluxos em Execução',
                'db_table': 'fluxos_instancia',
            },
        ),
        migrations.AddField(
            model_name='etapainstancia',
            name='fluxo_instancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='SISTEMA.fluxoinstancia'),
        ),
        migrations.AddField(
            model_name='movimentacaofluxo',
            name='fluxo_instancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='SISTEMA.fluxoinstancia'),
        ),
        migrations.DeleteModel(
            name='Assinatura',
        ),
        migrations.AlterUniqueTogether(
            name='etapainstancia',
            unique_together={('fluxo_instancia', 'ordem_etapa')},
        ),
    ]
