# Generated by Django 5.2.7 on 2025-11-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISTEMA', '0003_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxoinstancia',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
